= Introduction to Application Platforms and Platform Engineering
:navtitle: Home

== Introduction

Welcome to this quick course on the _**Introduction to Application Platforms and Platform Engineering**_.
This course is the `first` in a series of `six` courses about **Application Platform Delivery**:

* https://redhatquickcourses.github.io/etx-app-delivery-module1/etx-app-delivery-module1/1/index.html[_Introduction to Application Platforms and Platform Engineering_, window=browser] (_This course_)
* https://redhatquickcourses.github.io/etx-app-delivery-module2/etx-app-delivery-module2/1/index.html[_Software Factory Foundations with OpenShift Dev Spaces_, window=browser]
* https://redhatquickcourses.github.io/etx-app-delivery-module3/etx-app-delivery-module3/1/index.html[_Software Delivery with OpenShift Pipelines and GitOps_, window=browser]
* https://redhatquickcourses.github.io/etx-app-delivery-module4/etx-app-delivery-module4/1/index.html[_DevEx with Red Hat Developer Hub_, window=browser]
* https://redhatquickcourses.github.io/etx-app-delivery-module5/etx-app-delivery-module5/1/index.html[_Application Modernization with MTA_]
* _Trusted Software Supply Chain (TSSC)_ (Coming soon)

== What's in this course?

This course introduces Platform Engineering and Application Platforms, covering the evolution from DevOps to Platform Engineering, the role of Kubernetes and Application Platforms, how Red Hat OpenShift delivers an integrated platform, and the key roles involved in modern application delivery.

Duration: 30 minutes

== Contributors

The PTL team acknowledges the valuable contributions of the following Red Hat associates:

* Andrew Block (SME)
* Bill Wheatley (SME)
* Bryan Saunders (SME)
* Evan Shortiss (SME)
* Julio Villarreal Pelegrino (SME)
* Kristopher Godek (SME)
* Roman Martin Gil (SME)
* Senthil Kumar (SME)
* Sergio Canales Espinoza (SME)
* Yogita Soni (Content Architect)
* Lisa Edgell (Learning Product Manager)
* Caitlyn Rymarchyk (Learning Product Manager)
* Anna Swicegood (Learning Product Manager)

== Objectives

By the end of this module, you will be able to:

* Explain how software delivery evolved from DevOps to SRE and Platform Engineering.
* Describe the purpose and value of an Application Platform.
* Explain why Kubernetes alone is not sufficient for modern application delivery.
* Distinguish between a Container Management Platform and an Application Platform.
* Identify the key capabilities of a modern Application Platform, including application runtimes, builds, CI/CD, observability, security, and developer self-service.
* Describe how Red Hat OpenShift extends Kubernetes to provide an integrated Application Platform.
* Explain the roles and responsibilities of Operations Engineers, Platform Engineers, and Application Developers.
* Apply an Application Platform litmus test to evaluate whether a platform provides the capabilities and developer experience required for modern software delivery.

== Prerequisites

This course assumes that you have the following prior experience:

1. https://training-lms.redhat.com/lmt/clmscoursedetails.prmain?in_sessionId=5034892A2J492834&in_selfContained=N&in_offeringId=57857955&in_tab_group=&in_from_module=CLMSBROWSEV2.PRMAIN[Red Hat OpenShift Container Platform (OCP) Technical Overview] or Kubernetes Basics